export enum ProcedureName {
    OPEN_WELCOME_MAIL_POPUP = 'OPEN_WELCOME_MAIL_POPUP',
    DOWNLOAD_BILL = 'DOWNLOAD_BILL',
    OPEN_HOMOLOGATION = 'OPEN_HOMOLOGATION',
    SHOW_SUSPENSION_SMS ='SHOW_SUSPENSION_SMS',
    SHOW_ENTRY_REPORT_MAIL = 'SHOW_ENTRY_REPORT_MAIL'
}
