export const REFERENCE_DATA_PANIER = {
    LIVRAISON_PAR_COACH : { key: 'ref_delivery_mode_coach', value: 'Livraison par le Coach'},
    LIVRAISON_PAR_TECHNICIEN : { key: 'ref_delivery_mode_technician', value: 'Livraison par le Technicien'},
    LIVRAISON_PAR_COACH_PARIS : { key: 'ref_delivery_mode_coach_paris', value: 'Livraison par le Coach Paris'},
    LIVRAISON_PAR_COACH_RIVIERA : { key: 'ref_delivery_mode_coach_riviera', value : 'Livraison par le Coach Riviera'},
    LIVRAISON_COACH_SOUTIEN_MULTIMEDIA : { key: 'ref_delivery_mode_livraison_par_le_soutien_multimedia', value : 'Livraison par le Coach avec un Soutien Multimedia'},
    LIVRAISON_PAR_TECHNICIEN_PARIS : { key: 'ref_delivery_mode_technician_paris', value : 'Livraison par le Technicien Paris'},
    EVEMENTIEL : { key: 'ref_delivery_mode_specialEvent', value : 'Evènementiel'},
    AUTRE : { key: 'ref_delivery_mode_other', value : 'Autre'},
    PRESTATAIRE_LIVRAISON : { key: 'ref_delivery_mode_delivery_provider', value : 'Prestataire livraison'},
    LIVRAISON_PAR_COACH_AIX : { key: 'ref_delivery_mode_coach_aix', value: 'Livraison par le Coach Aix-en-Provence'},
    LIVRAISON_PAR_COACH_LYON : { key: 'ref_delivery_mode_coach_lyon', value: 'Livraison par le Coach Lyon'},
    LIVRAISON_PAR_COACH_ANNECY : { key: 'ref_delivery_mode_coach_annecy', value: 'Livraison par le Coach Annecy'},
    LIVRAISON_PAR_COACH_LILLE : { key: 'ref_delivery_mode_coach_lille', value: 'Livraison par le Coach Lille'},
    LIVRAISON_PAR_TECHNICIEN_AIX : { key: 'ref_delivery_mode_technician_aix', value: 'Livraison par le Technicien Aix-en-Provence'},
    LIVRAISON_PAR_TECHNICIEN_LILLE : { key: 'ref_delivery_mode_technician_lille', value: 'Livraison par le Technicien Lille'},
    LIVRAISON_PAR_TECHNICIEN_LYON : { key: 'ref_delivery_mode_technician_lyon', value: 'Livraison par le Technicien Lyon'},
    LIVRAISON_PAR_TECHNICIEN_ANNECY : { key: 'ref_delivery_mode_technician_annecy', value: 'Livraison par le Technicien Annecy'},
    LIVRAISON_PAR_TECHNICIEN_RIVIERA : { key: 'ref_delivery_mode_technician_riviera', value: 'Livraison par le Technicien Riviera'},
    LIVRAISON_PAR_COACH_RENNES : { key: 'ref_delivery_mode_coach_rennes', value: 'Livraison par le Coach Rennes'},
    LIVRAISON_PAR_COACH_NANTES : { key: 'ref_delivery_mode_coach_nantes', value: 'Livraison par le Coach Nantes'},
    LIVRAISON_PAR_COACH_CORSE_SUD : { key: 'ref_delivery_mode_coach_corsesud', value: 'Livraison par le Coach Corse du Sud'},
    LIVRAISON_PAR_COACH_NORMANDIE : { key: 'ref_delivery_mode_coach_normandie', value: 'Livraison par le Coach Normandie'},
    LIVRAISON_PAR_COACH_BORDEAUX : { key: 'ref_delivery_mode_coach_bordeaux', value: 'Livraison par le Coach Bordeaux'},
    LIVRAISON_PAR_COACH_TOULOUSE : { key: 'ref_delivery_mode_coach_toulouse', value: 'Livraison par le Coach Toulouse'},
    LIVRAISON_PAR_TECHNICIEN_RENNES : { key: 'ref_delivery_mode_technician_rennes', value: 'Livraison par le Technicien Rennes'},
    LIVRAISON_PAR_TECHNICIEN_NANTES : { key: 'ref_delivery_mode_technician_nantes', value: 'Livraison par le Technicien Nantes'},
    LIVRAISON_PAR_TECHNICIEN_CORSE_SUD : { key: 'ref_delivery_mode_technician_corsesud', value: 'Livraison par le Technicien Corse du Sud'},
    LIVRAISON_PAR_TECHNICIEN_NORMANDIE : { key: 'ref_delivery_mode_technician_normandie', value: 'Livraison par le Technicien Normandie'},
    LIVRAISON_PAR_TECHNICIEN_BORDEAUX : { key: 'ref_delivery_mode_technician_bordeaux', value: 'Livraison par le Technicien Bordeaux'},
    LIVRAISON_PAR_TECHNICIEN_TOULOUSE : { key: 'ref_delivery_mode_technician_toulouse', value: 'Livraison par le Technicien Toulouse'}
  }
export const CONF_ADDRESS_DELIVERY = {
  PARNASSE_ADRESSE_NAME: 'Parnasse -',
  PARNASSE_LOCATION_ADRESSE:'12B rue campagne première',
  PARNASSE_LOCATION_POSTAL_CODE:'75014',
  PARNASSE_LOCATION_CITY:'Paris',
  PARNASSE_LOCATION_COUNTRY_CODE:'FR',
  RIVIERA_ADRESSE_NAME:'Orange - Parnasse',
  RIVIERA_LOCATION_ADRESSE:'64 avenue de L\'Hubac',
  RIVIERA_LOCATION_POSTAL_CODE:'06250',
  RIVIERA_LOCATION_CITY:'MOUGINS',
  RIVIERA_LOCATION_COUNTRY_CODE:'FR',
  RIVIERA_RECEVEUR:'D_ROIG,T_SYLVESTRE',
  AIX_ADRESSE_NAME:'Orange Parnasse   - UI PRM',
  AIX_LOCATION_ADRESSE:'Impasse des frères Pratèsi',
  AIX_LOCATION_ADRESSE3:'Aix Bouffan',
  AIX_LOCATION_POSTAL_CODE:'13090',
  AIX_LOCATION_CITY:'Aix-en-Provence',
  AIX_LOCATION_COUNTRY_CODE:'FR',
  LYON_ADRESSE_NAME:'Orange Parnasse -  UI Aura',
  LYON_LOCATION_ADRESSE:'180 Allée Alexandre Borodine',
  LYON_LOCATION_POSTAL_CODE:'69800',
  LYON_LOCATION_CITY:'Saint-Priest',
  LYON_LOCATION_COUNTRY_CODE:'FR',
  LILLE_ADRESSE_NAME:'Orange Parnasse -  UI NdF',
  LILLE_LOCATION_ADRESSE:'51 -53 Rue Jean Bart',
  LILLE_LOCATION_POSTAL_CODE:'59260',
  LILLE_LOCATION_CITY:'Hellemmes',
  LILLE_LOCATION_COUNTRY_CODE:'FR',
  ANNECY_ADRESSE_NAME:'Orange Parnasse -  UI Aura',
  ANNECY_LOCATION_ADRESSE:'69 avenue des Romains',
  ANNECY_LOCATION_ADRESSE3:'CS 90355',
  ANNECY_LOCATION_POSTAL_CODE:'74012',
  ANNECY_LOCATION_CITY:'Annecy cedex',
  ANNECY_LOCATION_COUNTRY_CODE:'FR',
  RENNES_ADRESSE_NAME:'Orange',
  RENNES_LOCATION_ADRESSE:'8 rue Jacqueline Auriol',
  RENNES_LOCATION_POSTAL_CODE:'35136',
  RENNES_LOCATION_CITY:'Saint-Jacques-de-la-Lande',
  RENNES_LOCATION_COUNTRY_CODE:'FR',
  NANTES_ADRESSE_NAME:'Orange',
  NANTES_LOCATION_ADRESSE:'5 rue du moulin de la garde',
  NANTES_LOCATION_ADRESSE3:'Code 44M03',
  NANTES_LOCATION_POSTAL_CODE:'44300',
  NANTES_LOCATION_CITY:'Nantes',
  NANTES_LOCATION_COUNTRY_CODE:'FR',
  CORSE_SUD_ADRESSE_NAME:'Magasin Orange',
  CORSE_SUD_LOCATION_ADRESSE:'Chemin de Ranocchietto',
  CORSE_SUD_LOCATION_POSTAL_CODE:'20167',
  CORSE_SUD_LOCATION_CITY:'Ajaccio',
  CORSE_SUD_LOCATION_COUNTRY_CODE:'FR',
  NORMANDIE_ADRESSE_NAME:'Orange - Pole Activités Esperance',
  NORMANDIE_LOCATION_ADRESSE:'272 rue Edouard Branly',
  NORMANDIE_LOCATION_POSTAL_CODE:'14100',
  NORMANDIE_LOCATION_CITY:'Lisieux',
  NORMANDIE_LOCATION_COUNTRY_CODE:'FR',
  BORDEAUX_ADRESSE_NAME:'Orange - Poste sécu pour Parnasse',
  BORDEAUX_LOCATION_ADRESSE:'23 rue Thomas Edison',
  BORDEAUX_LOCATION_ADRESSE3:'JM. Caillavel ou S. Razainandrasana',
  BORDEAUX_LOCATION_POSTAL_CODE:'33600',
  BORDEAUX_LOCATION_CITY:'Pessac',
  BORDEAUX_LOCATION_COUNTRY_CODE:'FR',
  TOULOUSE_ADRESSE_NAME:'Orange  - UI OC',
  TOULOUSE_LOCATION_ADRESSE:'16 rue des Frères Peugeot',
  TOULOUSE_LOCATION_ADRESSE3:'Christophe André / Parnasse',
  TOULOUSE_LOCATION_POSTAL_CODE:'31130',
  TOULOUSE_LOCATION_CITY:'Balma',
  TOULOUSE_LOCATION_COUNTRY_CODE:'FR'
}
export const PUBLIDISPATCH = 'Publidispatch';
