import { FacturationLineVO } from './facturation-line-vo';
import { FamilyVO } from './family-vo';
import { NomenclatureVO } from './nomenclature-vo';
import { ProductVO } from './productVO';

export interface CustomerHardwareParkItemVO {
    id: number;
  status: string;
  subscriptionDate: Date;
  contactMethodPostalAddressId: number;
  delimitedContactMethodPostalAddress: string;
  createdAt: Date;
  createdById: number;
  createdByFullName: string;
  updatedAt: Date;
  updatedById: number;
  updatedByFullName: string;
  customerId: number;
  terminatedAt: Date;
  terminatedById: number;
  terminatedByFullName: string;
  comments: string;
  productLabel: string;
  associatedLineId: number;
  associatedLineIdentifier: string;
  productId: number;
  product: ProductVO;
  productFamily: FamilyVO;
  facturationLine: FacturationLineVO;
  billAccountIdentifier: string;
  recurrent: boolean;
  toInvoice: boolean;
  alreadyPaidInvoice: boolean;
  unreferencedProductCategory: FamilyVO;
  serial: string;
  masterProductName: string;
  productCategoryName: string;
  productCategoryKey: string;
  productFamilyName: string;
  productSubFamilyName: string;
  productQuantityBlocked: boolean;
  productSerialRequired: boolean;
  productDiscountIncluded: boolean;
  nbOffersAvailable: number;
  hasOffers: boolean;
  maxNbOffers: number;
  customerName: string;
  requestType: string;
  requestId: number;
  billLivrableURL: string;
  billFileName: string;
  billResolution: boolean;
  warrantyLabel: string;
  warrantyValue: number;
  articleClassId: number;
  manufacturerId: number;
  acquisitionPriceReal: number;
  nomenclature: NomenclatureVO;
  customerBeneficeryId: number;
  type: string;
  category: string;
  customerNicheIdentifier: string;
  offerLabel: string;
  customerBeneficeryName: string;
  billAccountNicheIdentifier: string;
  hardwareStatus : string;
}
