export type Status = "CREATED" | "CANCELED" | "ORDERED" | "WARNING" 
| "CONFIRMED" | "SENT" | "PARTIAL_SENT" | "REJECTED" | "ABANDONED" | "ERROR" 
| "DELIVERED" | "PARTIAL_DELIVERED" | "RETURNED" | "ON_TOUR" | "PARTIAL_ON_TOUR";
